[profile.default]
src = 'cache/solpp-generated-contracts'
out = 'artifacts-forge'
libs = ['node_modules', 'lib']
cache_path = 'cache-forge'
test = 'test/foundry'
solc_version = "0.8.25"
evm_version="cancun"

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
