[profile.default]
src = 'cache-zk/solpp-generated-contracts'
out = 'artifacts-forge'
libs = ['node_modules', 'lib']
cache_path = 'cache-zkfoundry'
test = 'test/foundry'

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
