name: L2 contracts CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build L1 artifacts
        run: yarn l1 build

      - name: Build L2 artifacts
        run: yarn l2 build

      - name: Create cache
        uses: actions/cache/save@v3
        with:
          key: artifacts-l2-${{ github.sha }}
          path: |
            l1-contracts/artifacts
            l1-contracts/cache
            l1-contracts/typechain
            l2-contracts/artifacts-zk
            l2-contracts/cache-zk
            l2-contracts/typechain

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint:check

  test:
    needs: [build, lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Restore artifacts cache
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          key: artifacts-l2-${{ github.sha }}
          path: |
            l1-contracts/artifacts
            l1-contracts/cache
            l1-contracts/typechain
            l2-contracts/artifacts-zk
            l2-contracts/cache-zk
            l2-contracts/typechain

      - name: Run Era test node
        uses: dutterbutter/era-test-node-action@v0.1.3

      - name: Run tests
        run: yarn l2 test
  
  gas-bound-caller:
    needs: [build, lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build GasBoundCaller
        run: yarn gas-bound-caller build

      - name: CHeck the correcntess of the canonical bytecode
        run: yarn gas-bound-caller calculate-canonical-bytecode:check

      - name: Use era-test-node for testing
        uses: dutterbutter/era-test-node-action@v0.1.3
        with:
          releaseTag: v0.0.1-vm1.5.0

      - name: Run tests
        run: yarn gas-bound-caller test
